### ISSUE TITLE
EPIC - Documentation

### ISSUE THREAD

**Issue by dantes-git** [ZupIT/beagle#1051]
We should create or update in documentation the following contents:

Common API:

- [x] AddChildren: mention default value
- [x] Condition: _condition_ should be Binding or Boolean
- [ ] Confirm: _onPressOK_, _onPressCancel_ should it be a list of actions?
- [x] Navigate:
    - Route.Remote: update _url_ to Binding or String
- [x] SendRequest:
    - _onSuccess_, _onError_ e _onFinish_ should be a List of Actions
    - _headers_ property should be bindable
- [x] Form: to be documented (Old Form)
- [x] FormLocalAction: to be documented
- [x] FormRemoteAction: to be documented
- [x] FormValidation: to be documented
- [x] SubmitForm: to be documented
- [x] Image: update _imagePath_ to Binding or ImagePath
- [x] TabBarItem: to be documented
- [ ] PageIndicator: is _selectedColor_ and _unselectedColor_ required?
- [ ] PageView: should we document the _pageIndicator_ parameter?
- [x] TextInput: must be removed from the form section
- [ ] Screen: Is the _identifier_ parameter correctly named? (on iOS it is named _id_)
- [x] Operations: to be documented
- [x] GlobalContext: update iOS samples

API iOS only:
- [ ] BeagleScreenViewController: to be documented
    - ScreenType: to be documented
- [ ] BeagleView: to be documented

Tutorials iOS:
- [ ] Using BeagleView

**Comment by dantes-git** [comment]
Already addressed
