### ISSUE TITLE
[POC] - Unifying Beagle's mobile functional tests using Appium 

### ISSUE THREAD

**Issue by igorgiumellizup** [ZupIT/beagle#1147]
## Problem:
Currently, Beagle's mobile platforms contains functional UI (User Interface) tests* written using BDD (Behavior Driven Development) tools such as [Cucumber](https://cucumber.io/). These platform tests have very similar test scenarios and implementation. In fact, whenever a new platform test scenario is implemented, it needs to be replicated or adapted to its counterpart platform and vice-versa. All this process generates duplicated code and unnecessary effort.

\* [Android ](https://github.com/ZupIT/beagle/tree/master/android/automated-tests/src/androidTest) | [iOS](https://github.com/ZupIT/beagle/tree/master/iOS/Tests/AutomatedTestsUITests)

## Suggested solution:
Unify identical \ very similar mobile platform UI tests. Create one implementation \ project that is able to test both mobile platforms using the same test scenario and implementation. [Appium](http://appium.io/) makes it possible to test both platforms with one implementation.  

## POC status:

POC source code: ~~https://github.com/igorgiumellizup/mobile_tests~~ https://github.com/ZupIT/beagle/tree/feature/beagle_appium_app/tests/appium

- [x] Create project structure (Kotlin + Gradle + Appium + Cucumber)
- [x] Validate some test scenarios on both platforms
- [x] Implement error reports using screenshots
- [x] Implement a mechanism to properly shutdown the driver after a test suite run, since Cucumber doesn't suport AfterAll \ AfterClass. 
- [x] Identify test scenarios that are different between platforms
  - ScrollView: very different. On Android it's not scrolling at all
  - Navigation: very different. Missing important scenarios on iOS. Currently it is only working on Android
- [x] Identify test scenarios that should be tested by snapshot approach (image comparison) or that should remain in 
  - ListView (platform only tests)
  - TextScreen (done)
- [x] Test successfully all common test scenarios on both platforms
  - ActionNotRegistered
  - AddChildren
  - Alert
  - Button
  - Conditional
  - Confirm
  - Container
  - Image
  - LazyComponente
  - PageView
  - SendRequest
  - SetContext
  - SimpleForm
  - TabBar
  - TextStyle (former TextScreen)
  - Touchable
  - TextInput
- [x] Improve iOS test run speed
- [x] Implement image comparison tests (snapshot tests) to validade elements style test scenarios    
- [ ] Create an Android deploy script (for GitHub Actions)
- [ ] Create an iOS deploy script (for GitHub Actions)
- [ ] Extract the utils code in AppiumUtils and AbstractStep to a lib, so that other projects that use Appium can benefit from it
