### ISSUE TITLE
[Epic] Implement component PullToRefresh

### ISSUE THREAD

**Issue by Tiagoperes** [ZupIT/beagle#1626]
# PullToRefresh
Related issue: https://github.com/ZupIT/beagle/issues/1569

PullToRefresh is a new component valid for any mobile platform (iOS, Android, React Native and Flutter). In Web platforms, this component should be ignored (it should't break the application).

The PullToRefresh component attaches an event to the view whenever it's pulled down by the user. The event  triggers an animation (spinner) and calls any Beagle action that has been associated with the event. The animation used is the default of each platform, the only customization we allow is the color of the spinner. For further customization, the user should check our implementation of the PullToRefresh and implement his/her own custom component.

## Usage

The PullToRefresh, just like the ScreenComponent, must be used only once per view. We recommend placing the PullToRefresh component as child of a ScreenComponent whenever you want the screen to have a pullToRefresh behavior. See the example below:

```json
{
  "_beagleComponent_": "beagle:screenComponent",
  "child": {
    "_beagleComponent_": "beagle:pullToRefresh",
    "onPull": [],
    "child": {
      "_beagleComponent_": "beagle:container",
      "children":[]
    }
  }
}
```

## Interface

```typescript
interface PullToRefresh {
  _beagleComponent_: 'beagle:pullToRefresh',
  context?: ContextData,
  onPull: Action[],
  isRefreshing?: Bindable<boolean>, // default is false
  color?: Bindable<string>, // default is whatever the system default is
  child: BeagleUIElement,
}
```

## Implementation

Most of this component has already been implemented by @luisgustavozup (Android) and @dantes-git (iOS). Please, check with them before starting any implementation.

## Tasks

- [X] Implement Android Component
- [ ] Implement iOS Component
- [ ] Implement Appium tests (e2e)
- [ ] Make React and Angular Ignore this component by interpreting it as a container
- [ ] Write documentation for the new Component
- [ ] Implement React Native Component (optional)
- [ ] Implement Flutter Component (optional)

**Comment by paulomeurerzup** [comment]
We're adding a Context to the component interface, so that the user will have a place to declare the context which will keep the component's state.

```Typescript
interface PullToRefresh {
  _beagleComponent_: 'beagle:pullToRefresh',
  context?: ContextData,
  onPull: Action[],
  isRefreshing?: Bindable<boolean>, // default is false
  color?: Bindable<string>, // default is whatever the system default is
  child?: BeagleUIElement,
}```

**Comment by paulomeurerzup** [comment]
We've agreed between Android and iOS platforms that updating the context referenced by isRefreshing to true won't trigger onPull actions.
