### ISSUE TITLE
EPIC - Create Beagle Schema to decouple our JSON contract from platforms that consume it

### ISSUE THREAD

**Issue by LG95** [ZupIT/beagle#40]
### Problem

Currently, Beagle's declarative module is composed of the models and contracts that the server-driven elements and actions must abide by.

This is the "`common`" module and is only directly importable by the backend and Android modules since it is Kotlin code. **Other languages need to manually translate these contracts**, which can result in discrepancies.

### Scope

Synchronize the contracts among all our platforms, using code generation. Provide a toolkit for Beagle to use internally and that projects using Beagle may use.

### Acceptance Criteria

- should be platform-independent but would not compromise any
- our definition format should be readable and typed, so the user can understand what they need to pass on each parameter (that's why just a JSON representation would not be good for us)
- extensible for automation and code generation, so we could generate APIs for new languages or platforms
- it would be good to let users use our format and toolkit to define their custom components

### Wishlist

- we will probably need some kind of "type inheritance" that will help us identify common behaviors of our components (e.g: Widget, Children, Appearance, Accessibility, Flex)
- we will probably need some kind of "restricted inheritance" or "limited set of types" (e.g: Kotlin's sealed class, Swift's enum with associated values, Typescript's union type). This would help us define our `NavigateAction` structure and maybe others that will come.
- we could use some form of rule definition, to define common rules and behaviors across platforms

**Comment by LG95** [comment]
- [ ] Choose the format for the schema
- [ ] Translate our models and contracts to this format
- [ ] Create Beagle Schema module in this repository
- [ ] Find or create a code generation tool

**Comment by tuliopereirazup** [comment]
@LG95 and @theffc can we consider this issue closed?

**Comment by theffc** [comment]
We did just the first part of this, and it was actually the most “straightforward” part, so I think all things in this issue are far from done

**Comment by LG95** [comment]
I agree with @theffc, but considering our discussion I have removed it from our 1.0 board, since the remaining parts will been done after it's release.

**Comment by dantes-git** [comment]
We discussed the original problem and solutions and decide to step back with this EPIC.
