### ISSUE TITLE
Beagle standardization

### ISSUE THREAD

**Issue by matheusribeirozup** [ZupIT/beagle#61]
**Describe the problem**
Currently Beagle has a usage context that is more focused on mobile and several points do not make sense for the web.

**Expected behavior**
For the use of a single BFF serving mobile and web, standardization of names, construction of components and separation between flex and style must be standardized.

**Steps**
- [x] Color Android
- [x] Color iOS
- [x] Change `Style` to `Theme` and change `Appearance` to `Style` Android
- [x] Change `Style` to `Theme` and change `Appearance` to `Style` iOS
- [x] Place the `Flex` inside the `Style` and remove from the `Flex` what should be in the `Style` (margin, position, padding, size, display, direction) Android
- [x] Place the `Flex` inside the `Style` and remove from the `Flex` what should be in the `Style` (margin, position, padding, size, display, direction) iOS
- [x] Add attributes within `Style` (color, backgroundColor, marginStart, marginEnd, paddingStart, paddingEnd) Android
- [x] Add attributes within `Style` (color, backgroundColor, marginStart, marginEnd, paddingStart, paddingEnd) iOS
- [x] Create a way to keep `applyFlex` external today without having to instantiate `Style` Android
- [x] Create a way to keep `applyFlex` external today without having to instantiate `Style` iOS
- [x] Change in Beagle whatever is rows, pages, etc. for `children` for the purpose of semantic coherence or whatever is more than one `child` should be called `children` Android
- [x] Change in Beagle whatever is rows, pages, etc. for `children` for the purpose of semantic coherence or whatever is more than one `child` should be called `children` iOS

**Linked issues**
#99 #100 #101 #103 #104
